ARG BASE_IMAGE=tfenn_a:latest
FROM ${BASE_IMAGE}

ARG OPLS_SOURCE_TREE_SHA256=1190ba588aa2bdf2ae8a60b894b1456ca64c34e0ddeeb6852b1c91113c92c2b8

COPY OPLS2020_Static /opt/OPLS2020_Static

RUN python -m pip install --no-deps --no-build-isolation \
        --editable /opt/OPLS2020_Static \
    && python -c "from importlib.metadata import version; from opls2020.io import code_provenance; expected='${OPLS_SOURCE_TREE_SHA256}'; actual=code_provenance()['source_tree_sha256']; assert version('opls2020-static') == '2.0.0'; assert actual == expected, (actual, expected)"

LABEL org.tfenn.opls.version="2.0.0"
LABEL org.tfenn.opls.source_tree_sha256="${OPLS_SOURCE_TREE_SHA256}"
