"""Generator compiled tensor mathematics for finite molecular symmetry."""

from .anchor_compiler import (
    AnchorBlock,
    AnchorCompilation,
    AnchorDimensions,
    compile_anchors,
)
from .covariants import scalar_contraction, vector_covariant
from .intertwiner_compiler import (
    BilinearIntertwinerCompilation,
    IntertwinerCompilation,
    a_representation,
    compile_bilinear_intertwiners,
    compile_intertwiners,
    direct_sum_representation,
    intertwiner_residual,
    tensor_product_representation,
)
from .pose_encoding import PoseEncoder
from .stf_rep import stf_representation, symmetric_representation, validate_rotation
from .stf_space import (
    MAX_STF_RANK,
    STF_BASIS_VERSION,
    TENSOR_CONVENTION_VERSION,
    dense_to_stf,
    dense_to_symmetric,
    project_symmetric,
    stf_basis,
    stf_dimension,
    stf_power_components,
    stf_symmetric_product,
    stf_tensor_coupling,
    stf_to_dense,
    stf_to_symmetric,
    symmetric_dimension,
    symmetric_multi_indices,
    symmetric_power_components,
    symmetric_to_dense,
    symmetric_to_stf,
    trace_matrix,
)


__all__ = [
    "AnchorBlock",
    "AnchorCompilation",
    "AnchorDimensions",
    "BilinearIntertwinerCompilation",
    "IntertwinerCompilation",
    "MAX_STF_RANK",
    "PoseEncoder",
    "STF_BASIS_VERSION",
    "TENSOR_CONVENTION_VERSION",
    "a_representation",
    "compile_anchors",
    "compile_bilinear_intertwiners",
    "compile_intertwiners",
    "dense_to_stf",
    "dense_to_symmetric",
    "direct_sum_representation",
    "intertwiner_residual",
    "project_symmetric",
    "scalar_contraction",
    "stf_basis",
    "stf_dimension",
    "stf_power_components",
    "stf_representation",
    "stf_symmetric_product",
    "stf_tensor_coupling",
    "stf_to_dense",
    "stf_to_symmetric",
    "symmetric_dimension",
    "symmetric_multi_indices",
    "symmetric_power_components",
    "symmetric_representation",
    "symmetric_to_dense",
    "symmetric_to_stf",
    "tensor_product_representation",
    "trace_matrix",
    "validate_rotation",
    "vector_covariant",
]
