r"""Compile canonical invariant STF anchor spaces for finite rotation groups.

This module owns the offline construction of fixed, generated, and primitive
anchor spaces.  Its major public APIs are :class:`AnchorCompilation`,
:class:`AnchorBlock`, :class:`AnchorDimensions`, and :func:`compile_anchors`.
For Python ``rank`` and mathematical ``l`` in the integers from one through
``MAX_STF_RANK``, let ``d_l = 2 l + 1`` and

``K_l_fix = Fix_H(V_l)``,
``K_l_gen`` be the invariant subspace generated by couplings of lower rank
primitive anchors, and
``K_l_prim = K_l_fix intersect orthogonal_complement(K_l_gen)``.

Generators have exact shape ``(generator_count, 3, 3)`` and represent active
column vector rotations from a body frame to a common frame.  Every compiled
basis has shape ``(2 * rank + 1, multiplicity)``.  ``output_ranks`` names only
requested network outputs.  The compiler internally scans every rank from one
through the largest requested rank so that lower rank anchors can generate
higher rank descendants.  Scan diagnostics never implicitly become outputs.
There are no batch axes other than the leading generator axis.

Compilation detaches all inputs, performs the numerical work without autograd,
and returns CPU float64 tensors.  Runtime dtype, device, and gradient behavior
belongs to :mod:`pose_encoding`.  Canonical projector ordering removes ordinary
sign and basis ordering freedom, but exact bits can still depend on the PyTorch
linear algebra backend.  A result is accepted only when its singular gap and
coupling leakage are separated from the configured numerical thresholds.  A
rank decision must also lie at least one half threshold away from its cutoff.

Type errors report unsupported Python values and tensor dtypes.  Value errors
report invalid shapes, ranks, tolerances, nonfinite data, and matrices outside
SO(3).  Runtime errors report unstable numerical subspaces and closure failures
with rank, residual, threshold, and actual and expected shapes.

Mapped references: Taco S. Cohen, Mario Geiger, Maurice Weiler,
``A General Theory of Equivariant CNNs on Homogeneous Spaces``,
https://proceedings.neurips.cc/paper/2019/hash/b9cfe8b6042cf759dc4c0cccb27a6737-Abstract.html;
Risi Kondor, Shubhendu Trivedi,
``On the Generalization of Equivariance and Convolution in Neural Networks to
the Action of Compact Groups``, https://proceedings.mlr.press/v80/kondor18a.html;
Dmitry Yarotsky, ``Universal Approximations of Invariant Maps by Neural
Networks``, https://arxiv.org/abs/1804.10306.
"""

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Iterable, Mapping, Sequence

import torch
from torch import Tensor

from ._compiler_utils import (
    canonical_column_space,
    canonical_nullspace,
    canonical_projector_basis,
    minimum_stable_margin,
    positive_finite_tolerance,
)
from .stf_rep import stf_representation
from .stf_space import MAX_STF_RANK, TENSOR_CONVENTION_VERSION, stf_tensor_coupling


__all__ = [
    "AnchorBlock",
    "AnchorCompilation",
    "AnchorDimensions",
    "compile_anchors",
]


ANCHOR_CONVENTION_VERSION = (
    f"{TENSOR_CONVENTION_VERSION}_active_column_primitive_v2"
)


@dataclass(frozen=True)
class AnchorDimensions:
    """Store fixed, generated, and primitive subspace dimensions."""

    fixed: int
    generated: int
    primitive: int


@dataclass(frozen=True)
class AnchorBlock:
    """Store one scanned rank and its canonical invariant subspaces."""

    rank: int
    fixed_basis: Tensor
    generated_basis: Tensor
    primitive_basis: Tensor
    constraint_residual: float
    generated_projection_residual: float
    generated_projection_threshold: float
    dimensions: AnchorDimensions
    singular_values: Tensor
    nullspace_threshold: float
    singular_value_gap: float
    threshold_margin: float


@dataclass(frozen=True)
class AnchorCompilation:
    """Store one stable CPU float64 anchor compilation record."""

    requested_output_ranks: tuple[int, ...]
    output_ranks: tuple[int, ...]
    scanned_ranks: tuple[int, ...]
    scanned_blocks: tuple[AnchorBlock, ...]
    generator_count: int
    generators: Tensor
    convention_version: str
    nullspace_atol: float
    nullspace_rtol: float
    rotation_atol: float
    rotation_rtol: float

    @property
    def blocks(self) -> Mapping[int, AnchorBlock]:
        """Return a read only mapping of scanned diagnostic blocks."""
        return MappingProxyType({block.rank: block for block in self.scanned_blocks})

    @property
    def primitive_anchors(self) -> Mapping[int, Tensor]:
        """Return cloned primitive matrices for nonempty requested outputs."""
        scanned = self.blocks
        return MappingProxyType(
            {
                rank: scanned[rank].primitive_basis.detach().clone()
                for rank in self.output_ranks
            }
        )

    @property
    def encoding_dimension(self) -> int:
        """Return the flattened dimension of requested primitive outputs."""
        scanned = self.blocks
        return sum(
            (2 * rank + 1) * scanned[rank].dimensions.primitive
            for rank in self.output_ranks
        )

    @property
    def residual(self) -> float:
        """Return the largest scanned generator constraint residual."""
        return max(
            (block.constraint_residual for block in self.scanned_blocks),
            default=0.0,
        )

    @property
    def dimensions(self) -> Mapping[int, AnchorDimensions]:
        """Return read only dimensions for every internally scanned rank."""
        return MappingProxyType(
            {block.rank: block.dimensions for block in self.scanned_blocks}
        )


def _as_generators(generators: Tensor | Sequence[Tensor]) -> Tensor:
    """Coerce generators to one real floating tensor."""
    if isinstance(generators, Tensor):
        matrices = generators.unsqueeze(0) if generators.ndim == 2 else generators
    else:
        items = list(generators)
        if not items:
            return torch.empty((0, 3, 3), dtype=torch.float64)
        matrices = torch.stack([torch.as_tensor(item) for item in items])
    if matrices.ndim != 3 or matrices.shape[1:] != (3, 3):
        raise ValueError(
            "generators actual shape "
            f"{tuple(matrices.shape)}; expected shape (count, 3, 3)"
        )
    if matrices.dtype not in (torch.float32, torch.float64):
        raise TypeError("generators must use float32 or float64")
    if not bool(torch.isfinite(matrices).all()):
        raise ValueError("generators must contain only finite values")
    return matrices


def _validate_rotations(matrices: Tensor, atol: float, rtol: float) -> None:
    """Require proper orthogonal generator matrices."""
    if matrices.shape[0] == 0:
        return
    identity = torch.eye(3, dtype=matrices.dtype, device=matrices.device)
    gram_error = (
        (matrices.transpose(-1, -2) @ matrices - identity).abs().amax(dim=(-2, -1))
    )
    determinant_error = (torch.linalg.det(matrices) - 1.0).abs()
    residual = float(torch.maximum(gram_error, determinant_error).amax())
    threshold = atol + rtol
    if residual > threshold:
        raise ValueError(
            "generators must belong to SO(3); "
            f"residual {residual:.6e}; threshold {threshold:.6e}; "
            f"actual shape {tuple(matrices.shape)}; "
            f"expected shape ({matrices.shape[0]}, 3, 3)"
        )


def _selected_output_ranks(output_ranks: int | Iterable[int]) -> tuple[int, ...]:
    """Validate and sort requested positive STF output ranks."""
    values = (output_ranks,) if isinstance(output_ranks, int) else tuple(output_ranks)
    if not values:
        raise ValueError("output_ranks must not be empty")
    if any(
        isinstance(rank, bool) or not isinstance(rank, int) or rank < 1
        for rank in values
    ):
        raise ValueError("output_ranks must contain positive integers")
    largest = max(values)
    if largest > MAX_STF_RANK:
        raise ValueError(
            f"rank {largest} exceeds project maximum {MAX_STF_RANK}; "
            f"actual shape ({largest},); expected shape (rank at most {MAX_STF_RANK},)"
        )
    return tuple(sorted(set(values)))


def _orthonormal_span(
    matrix: Tensor,
    atol: float,
    rtol: float,
    rank: int,
) -> Tensor:
    """Return a deterministic orthonormal basis for a column span."""
    result = canonical_column_space(matrix, atol, rtol)
    required_margin = minimum_stable_margin(result.threshold)
    if (
        result.singular_value_gap <= result.threshold
        or result.threshold_margin < required_margin
    ):
        raise RuntimeError(
            f"rank {rank} generated span has an unstable singular decision; "
            f"residual {result.residual:.6e}; "
            f"margin {result.threshold_margin:.6e}; "
            f"threshold {result.threshold:.6e}; "
            f"required margin {required_margin:.6e}; "
            f"actual shape {tuple(result.basis.shape)}; "
            f"expected shape ({matrix.shape[0]}, stable numerical rank)"
        )
    return result.basis


def _coupling_error(
    rank: int,
    residual: float,
    threshold: float,
    actual_shape: tuple[int, ...],
    expected_shape: tuple[int, ...],
) -> RuntimeError:
    """Build one complete coupling leakage error."""
    return RuntimeError(
        f"rank {rank} coupling leakage; residual {residual:.6e}; "
        f"threshold {threshold:.6e}; actual shape {actual_shape}; "
        f"expected shape {expected_shape}"
    )


def _generated_coupling_closure(
    primitive: dict[int, Tensor],
    fixed_spaces: dict[int, Tensor],
    target_rank: int,
    atol: float,
    rtol: float,
) -> tuple[Tensor, float, float]:
    """Close lower primitive anchors under every STF tensor coupling."""
    known = {
        rank: (
            primitive[rank].clone()
            if rank in primitive and rank < target_rank
            else fixed.new_empty((2 * rank + 1, 0))
        )
        for rank, fixed in fixed_spaces.items()
    }
    frontier = {rank: space.clone() for rank, space in known.items()}
    capacity = sum(fixed.shape[1] for fixed in fixed_spaces.values())
    largest_leakage = 0.0
    largest_threshold = atol

    for _ in range(capacity + 1):
        candidates: dict[int, list[Tensor]] = {rank: [] for rank in known}
        for rank_left, left in frontier.items():
            if left.shape[1] == 0:
                continue
            for rank_right, right in known.items():
                if right.shape[1] == 0:
                    continue
                highest = min(rank_left + rank_right, target_rank)
                for output_rank in range(
                    max(1, abs(rank_left - rank_right)), highest + 1
                ):
                    if (
                        known[output_rank].shape[1]
                        == fixed_spaces[output_rank].shape[1]
                    ):
                        continue
                    coupled = stf_tensor_coupling(
                        left.T[:, None],
                        right.T[None],
                        rank_left,
                        rank_right,
                        output_rank,
                    )
                    candidates[output_rank].append(
                        coupled.reshape(-1, 2 * output_rank + 1).T
                    )

        updated: dict[int, Tensor] = {}
        next_frontier: dict[int, Tensor] = {}
        grew = False
        for rank, fixed in fixed_spaces.items():
            if candidates[rank]:
                raw_candidates = torch.cat(candidates[rank], dim=1)
                expected_shape = (fixed.shape[0], raw_candidates.shape[1])
                if tuple(raw_candidates.shape) != expected_shape:
                    raise _coupling_error(
                        rank,
                        float("inf"),
                        0.0,
                        tuple(raw_candidates.shape),
                        expected_shape,
                    )
                projected = fixed @ (fixed.T @ raw_candidates)
                leakage_columns = torch.linalg.vector_norm(
                    raw_candidates - projected,
                    dim=0,
                )
                scale_columns = torch.linalg.vector_norm(raw_candidates, dim=0)
                leakage = (
                    float(leakage_columns.amax()) if leakage_columns.numel() else 0.0
                )
                scale = float(scale_columns.amax()) if scale_columns.numel() else 0.0
                threshold = atol + rtol * scale
                if leakage > threshold:
                    raise _coupling_error(
                        rank,
                        leakage,
                        threshold,
                        tuple(raw_candidates.shape),
                        expected_shape,
                    )
                largest_leakage = max(largest_leakage, leakage)
                largest_threshold = max(largest_threshold, threshold)
                updated[rank] = _orthonormal_span(
                    torch.cat((known[rank], projected), dim=1),
                    atol,
                    rtol,
                    rank,
                )
            else:
                updated[rank] = known[rank]
            increase = updated[rank].shape[1] - known[rank].shape[1]
            if increase < 0 or updated[rank].shape[1] > fixed.shape[1]:
                residual = float(abs(increase))
                raise RuntimeError(
                    f"rank {rank} generated invariant dimension is inconsistent; "
                    f"residual {residual:.6e}; threshold 0.000000e+00; "
                    f"actual shape {tuple(updated[rank].shape)}; "
                    f"expected shape ({fixed.shape[0]}, at most {fixed.shape[1]})"
                )
            if increase:
                grew = True
                projector = updated[rank] @ updated[rank].T
                projector = projector - known[rank] @ known[rank].T
                projector = 0.5 * (projector + projector.T)
                next_frontier[rank] = canonical_projector_basis(projector, increase)
            else:
                next_frontier[rank] = fixed.new_empty((2 * rank + 1, 0))
        known = updated
        frontier = next_frontier
        if known[target_rank].shape[1] == fixed_spaces[target_rank].shape[1]:
            return known[target_rank], largest_leakage, largest_threshold
        if not grew:
            return known[target_rank], largest_leakage, largest_threshold

    actual_shape = tuple(known[target_rank].shape)
    expected_shape = tuple(fixed_spaces[target_rank].shape)
    raise RuntimeError(
        f"rank {target_rank} generated coupling closure did not converge; "
        f"residual {largest_leakage:.6e}; threshold {largest_threshold:.6e}; "
        f"actual shape {actual_shape}; expected shape {expected_shape}"
    )


def compile_anchors(
    generators: Tensor | Sequence[Tensor],
    output_ranks: int | Iterable[int],
    *,
    nullspace_atol: float | None = None,
    nullspace_rtol: float | None = None,
    rotation_atol: float | None = None,
    rotation_rtol: float | None = None,
) -> AnchorCompilation:
    """Compile requested primitive anchors and all required scan diagnostics."""
    selected = _selected_output_ranks(output_ranks)
    source = _as_generators(generators)
    source_dtype = source.dtype
    default_atol = 1e-6 if source_dtype == torch.float32 else 1e-10
    resolved_nullspace_atol = positive_finite_tolerance(
        nullspace_atol,
        "nullspace_atol",
        default_atol,
    )
    resolved_nullspace_rtol = positive_finite_tolerance(
        nullspace_rtol,
        "nullspace_rtol",
        1e-12,
    )
    resolved_rotation_atol = positive_finite_tolerance(
        rotation_atol,
        "rotation_atol",
        default_atol,
    )
    resolved_rotation_rtol = positive_finite_tolerance(
        rotation_rtol,
        "rotation_rtol",
        default_atol,
    )
    matrices = source.detach().to(device="cpu", dtype=torch.float64)
    scanned_ranks = tuple(range(1, max(selected) + 1))
    _validate_rotations(
        matrices,
        resolved_rotation_atol,
        resolved_rotation_rtol,
    )
    blocks: list[AnchorBlock] = []
    primitive: dict[int, Tensor] = {}
    fixed_spaces: dict[int, Tensor] = {}

    with torch.no_grad():
        for rank in scanned_ranks:
            dimension = 2 * rank + 1
            identity = torch.eye(dimension, dtype=torch.float64)
            represented = stf_representation(
                matrices,
                rank,
                rotation_atol=resolved_rotation_atol,
                rotation_rtol=resolved_rotation_rtol,
            )
            constraints = (represented - identity).reshape(-1, dimension)
            expected_constraint_shape = (matrices.shape[0] * dimension, dimension)
            if tuple(constraints.shape) != expected_constraint_shape:
                raise RuntimeError(
                    f"rank {rank} constraint shape is inconsistent; residual inf; "
                    "threshold 0.000000e+00; "
                    f"actual shape {tuple(constraints.shape)}; "
                    f"expected shape {expected_constraint_shape}"
                )
            nullspace = canonical_nullspace(
                constraints,
                resolved_nullspace_atol,
                resolved_nullspace_rtol,
            )
            expected_basis_shape = (dimension, nullspace.dimension)
            required_margin = minimum_stable_margin(nullspace.threshold)
            if (
                nullspace.singular_value_gap <= nullspace.threshold
                or nullspace.threshold_margin < required_margin
            ):
                raise RuntimeError(
                    f"rank {rank} has an unstable singular decision; "
                    f"residual {nullspace.residual:.6e}; "
                    f"margin {nullspace.threshold_margin:.6e}; "
                    f"threshold {nullspace.threshold:.6e}; "
                    f"required margin {required_margin:.6e}; "
                    f"actual shape {tuple(nullspace.basis.shape)}; "
                    f"expected shape {expected_basis_shape}"
                )
            if nullspace.residual > nullspace.threshold:
                raise RuntimeError(
                    f"rank {rank} fixed space constraint is unstable; "
                    f"residual {nullspace.residual:.6e}; "
                    f"threshold {nullspace.threshold:.6e}; "
                    f"actual shape {tuple(nullspace.basis.shape)}; "
                    f"expected shape {expected_basis_shape}"
                )
            fixed = nullspace.basis
            fixed_spaces[rank] = fixed
            generated, leakage, leakage_threshold = _generated_coupling_closure(
                primitive,
                fixed_spaces,
                rank,
                resolved_nullspace_atol,
                resolved_nullspace_rtol,
            )
            fixed_projector = fixed @ fixed.T
            primitive_dimension = fixed.shape[1] - generated.shape[1]
            if primitive_dimension < 0:
                raise RuntimeError(
                    f"rank {rank} generated space exceeds fixed space; "
                    f"residual {float(-primitive_dimension):.6e}; "
                    "threshold 0.000000e+00; "
                    f"actual shape {tuple(generated.shape)}; "
                    f"expected shape ({dimension}, at most {fixed.shape[1]})"
                )
            primitive_projector = fixed_projector - generated @ generated.T
            primitive_projector = 0.5 * (primitive_projector + primitive_projector.T)
            retained = canonical_projector_basis(
                primitive_projector,
                primitive_dimension,
            )
            primitive[rank] = retained
            blocks.append(
                AnchorBlock(
                    rank=rank,
                    fixed_basis=fixed.detach().clone(),
                    generated_basis=generated.detach().clone(),
                    primitive_basis=retained.detach().clone(),
                    constraint_residual=nullspace.residual,
                    generated_projection_residual=leakage,
                    generated_projection_threshold=leakage_threshold,
                    dimensions=AnchorDimensions(
                        fixed=fixed.shape[1],
                        generated=generated.shape[1],
                        primitive=retained.shape[1],
                    ),
                    singular_values=nullspace.singular_values.detach().clone(),
                    nullspace_threshold=nullspace.threshold,
                    singular_value_gap=nullspace.singular_value_gap,
                    threshold_margin=nullspace.threshold_margin,
                )
            )

    output_ranks_result = tuple(
        rank for rank in selected if primitive[rank].shape[1] > 0
    )
    return AnchorCompilation(
        requested_output_ranks=selected,
        output_ranks=output_ranks_result,
        scanned_ranks=scanned_ranks,
        scanned_blocks=tuple(blocks),
        generator_count=matrices.shape[0],
        generators=matrices.detach().clone(),
        convention_version=ANCHOR_CONVENTION_VERSION,
        nullspace_atol=resolved_nullspace_atol,
        nullspace_rtol=resolved_nullspace_rtol,
        rotation_atol=resolved_rotation_atol,
        rotation_rtol=resolved_rotation_rtol,
    )
